// Code generated by mockery. DO NOT EDIT.

package mock_syncinterfaces

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// EthermanGetLastestBlockNumber is an autogenerated mock type for the EthermanGetLastestBlockNumber type
type EthermanGetLastestBlockNumber struct {
	mock.Mock
}

type EthermanGetLastestBlockNumber_Expecter struct {
	mock *mock.Mock
}

func (_m *EthermanGetLastestBlockNumber) EXPECT() *EthermanGetLastestBlockNumber_Expecter {
	return &EthermanGetLastestBlockNumber_Expecter{mock: &_m.Mock}
}

// GetLatestBlockNumber provides a mock function with given fields: ctx
func (_m *EthermanGetLastestBlockNumber) GetLatestBlockNumber(ctx context.Context) (uint64, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetLatestBlockNumber")
	}

	var r0 uint64
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) (uint64, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) uint64); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Get(0).(uint64)
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// EthermanGetLastestBlockNumber_GetLatestBlockNumber_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetLatestBlockNumber'
type EthermanGetLastestBlockNumber_GetLatestBlockNumber_Call struct {
	*mock.Call
}

// GetLatestBlockNumber is a helper method to define mock.On call
//   - ctx context.Context
func (_e *EthermanGetLastestBlockNumber_Expecter) GetLatestBlockNumber(ctx interface{}) *EthermanGetLastestBlockNumber_GetLatestBlockNumber_Call {
	return &EthermanGetLastestBlockNumber_GetLatestBlockNumber_Call{Call: _e.mock.On("GetLatestBlockNumber", ctx)}
}

func (_c *EthermanGetLastestBlockNumber_GetLatestBlockNumber_Call) Run(run func(ctx context.Context)) *EthermanGetLastestBlockNumber_GetLatestBlockNumber_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *EthermanGetLastestBlockNumber_GetLatestBlockNumber_Call) Return(_a0 uint64, _a1 error) *EthermanGetLastestBlockNumber_GetLatestBlockNumber_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *EthermanGetLastestBlockNumber_GetLatestBlockNumber_Call) RunAndReturn(run func(context.Context) (uint64, error)) *EthermanGetLastestBlockNumber_GetLatestBlockNumber_Call {
	_c.Call.Return(run)
	return _c
}

// NewEthermanGetLastestBlockNumber creates a new instance of EthermanGetLastestBlockNumber. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewEthermanGetLastestBlockNumber(t interface {
	mock.TestingT
	Cleanup(func())
}) *EthermanGetLastestBlockNumber {
	mock := &EthermanGetLastestBlockNumber{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
